### ISSUE TITLE
getpost url 표기오류

### ISSUE THREAD

**Issue by iseolin76** [Promotion-official/bamboo-server#28]
샘플 url 을 보면 post가 pist로 적혀있습니다.

**Comment by sunrabbit123** [comment]
[https://github.com/Promotion-official/bamboo-server/commit/a9481eededad95332bab85a67d060d72c4770375](https://github.com/Promotion-official/bamboo-server/commit/a9481eededad95332bab85a67d060d72c4770375)  
시정하였사옵니다.
